### ISSUE TITLE
make error occurred

### ISSUE THREAD

**Issue by yangchaoFree** [leon-bckl/lsp-framework#16]
in my ubuntu22.04 env,  gcc version is gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0.

cmake is ok.
there is errors when run make:

/usr/include/c++/11/bits/unordered_map.h:105:18:   required from ‘class std::unordered_map<std::__cxx11::basic_string<char>, lsp::json::Any, lsp::TransparentStrHash, std::equal_to<void>, std::allocator<std::pair<const std::__cxx11::basic_string<char>, lsp::json::Any> > >’
/home/ll/data/dev/ide/lsp/lsp-framework/lsp/json/json.h:52:23:   required from here
/usr/include/c++/11/bits/stl_pair.h:218:11: error: ‘std::pair<_T1, _T2>::second’ has incomplete type
  218 |       _T2 second;                ///< The second member
      |           ^~~~~~
In file included from /home/ll/data/dev/ide/lsp/lsp-framework/lspgen/lspgen.cpp:10:
/home/ll/data/dev/ide/lsp/lsp-framework/lsp/json/json.h:17:7: note: forward declaration of ‘class lsp::json::Any’
   17 | class Any;
      |       ^~~
make[2]: *** [CMakeFiles/lspgen.dir/build.make:76: CMakeFiles/lspgen.dir/lspgen/lspgen.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:85: CMakeFiles/lspgen.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by leon-bckl** [comment]
Works fine with gcc 13.3 on ubuntu (wsl)
